name: "build"

on:
  push:
    branches:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml

  upload:
    name: "Build"
    runs-on: "ubuntu-latest"

    permissions: write-all

    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: |
            SMEI.exe
