name: "release"

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    uses: ./.github/workflows/build-base.yml

  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    needs: build

    permissions: write-all

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: version

      - uses: "marvinpinto/action-automatic-releases@latest"
        name: Create prerelease
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automatic Pre-Release"
          files: |
            README.md
            SMEI.exe
